version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golfdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/golfdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: