basePath: /
definitions:
  AppError:
    description: Error that can be returned by the application
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  Course:
    description: Model for a golf course
    properties:
      compact:
        type: boolean
      golf_id:
        type: string
      id:
        type: string
      name:
        type: string
      num_holes:
        type: integer
      pitch_and_putt:
        type: boolean
    type: object
  Golf:
    description: Model for a golf
    properties:
      city:
        description: '@Description City where the golf course is located'
        example: Monterey
        type: string
      googleMapLinks:
        description: '@Description Google Maps link for the golf course'
        example: https://maps.google.com/?q=Pebble+Beach
        type: string
      id:
        type: string
      latitude:
        description: '@Description Latitude of the golf course'
        example: 36.567
        type: number
      longitude:
        description: '@Description Longitude of the golf course'
        example: -121.95
        type: number
      name:
        description: '@Description Name of the golf course'
        example: Pebble Beach
        type: string
      postalCode:
        description: '@Description Postal code of the golf course location'
        example: "93953"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This project is a comprehensive golf management system designed to
    facilitate the management of golf courses, including tracking of golf courses,
    holes, and tees.
  title: ProjectPAR API
  version: "1.0"
paths:
  /v1/courses:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Course'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Get all courses
      tags:
      - Courses
    post:
      consumes:
      - application/json
      parameters:
      - description: Course
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/Course'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Create a new course
      tags:
      - Courses
  /v1/courses/{id}:
    delete:
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Delete a course by ID
      tags:
      - Courses
    get:
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Get a course by ID
      tags:
      - Courses
    patch:
      consumes:
      - application/json
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      - description: Course
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/Course'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Course'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Update a course by ID
      tags:
      - Courses
  /v1/golfs:
    get:
      description: Get all golfs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Golf'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Get all golfs
      tags:
      - Golfs
    post:
      consumes:
      - application/json
      description: Create a new golf
      parameters:
      - description: Golf
        in: body
        name: golf
        required: true
        schema:
          $ref: '#/definitions/Golf'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Golf'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Create a new golf
      tags:
      - Golfs
  /v1/golfs/{id}:
    delete:
      description: Delete an existing golf by ID
      parameters:
      - description: Golf ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Delete an existing golf
      tags:
      - Golfs
    get:
      description: Get a golf by ID
      parameters:
      - description: Golf ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Golf'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Get a golf by ID
      tags:
      - Golfs
    patch:
      consumes:
      - application/json
      description: Update an existing golf by ID
      parameters:
      - description: Golf ID
        in: path
        name: id
        required: true
        type: string
      - description: Golf
        in: body
        name: golf
        required: true
        schema:
          $ref: '#/definitions/Golf'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Golf'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/AppError'
      summary: Update an existing golf
      tags:
      - Golfs
swagger: "2.0"
